### ISSUE TITLE
Blurred moving view

### ISSUE THREAD

**Issue by niteshkhatri** [qiujuer/ImageBlurring#5]
Hi, I am using your code in my application. However their is a slight problem. The view which have blurred is movable. When I click on a button, the blurred view (TextView) translates to different position. I want the blurred TextView to show blurred background in run time. I mean whichever part of the full image comes behind the TextView, while its moving, should be blurred. Is it possible? How can I achieve it?

Thanks.

**Comment by qiujuer** [comment]
This way, the difficulty lies in the dynamic gain the background behind the TextView, then the background compression and blured and assignment.
I think I can realize, but will take time to test efficiency.

**Comment by niteshkhatri** [comment]
I need to implement this urgently. Can you please write down this part of the code as well?

**Comment by qiujuer** [comment]
I Add new AnimatorBlurFragment example, I don't know whether you want this.
