### ISSUE TITLE
Appcrash when running on Genymotion Emulator

### ISSUE THREAD

**Issue by DavidLoveAnna** [qiujuer/ImageBlurring#6]
Hi, I have tried your code, and the fastBlur actually will cause crash on Genymotion Emulator, not all of them, but a few emulators, for example, Galaxy S5-4.4.2-API19 1080x1920, 480dpi

Here is the exception:
    java.lang.ArrayIndexOutOfBoundsException: length=112896; index=113033
            at net.qiujuer.imageblurring.util.FastBlur.doBlur(FastBlur.java:155)
            at net.qiujuer.imageblurring.fragments.FastBlurFragment.blur(FastBlurFragment.java:83)

Do you know what this could be?
Thanks.

**Comment by qiujuer** [comment]
Okay, I'll make sure this error, thank you.

**Comment by qiujuer** [comment]
Okay, that running mode will have this problem, but the debug mode is ok.
I suspect that the BUG is compiled in the run mode.
